spring.application.name=fraudriskanalyzer
spring.mongodb.uri=mongodb+srv://anjnajagatiya_db_user:BuvkSKgOXv2eyYLP@fraud-risk-cluster.fyrxjtl.mongodb.net/frauddb?appName=fraud-risk-cluster
jwt.secret=this-is-a-temporary-secret-key-change-it-later-make-it-long-and-random-32chars-min